# General simulation settings and paths
beamng_path: "C:/Users/Dan/Desktop/BeamNG.tech.v0.35.5.0"
user_path: "C:/Users/Dan/AppData/Local/BeamNG.drive"
port: 25252

# Paths (Use absolute paths for robustness, especially for the shared drive)
data_path: "data"

target_data_filename: "target_bolide.csv"
model_save_dirname: "training_runs"
log_dirname: "tensorboard_logs"

# Scenario Settings
map: "gridmap_v2"
base_vehicle_model: "etk800" 
base_vehicle_config: "vehicles/etk800/carl_base.pc"
target_vehicle_model: "racetruck"
target_vehicle_config: "C:/Users/Dan/Desktop/BeamNG.tech.v0.35.5.0/content/vehicles/racetruck.zip/vehicles/racetruck/tt2_spec.pc"